<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>SonicSearchService</AssemblyName>
    <RootNamespace>SonicSearch.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NtfsReader\NtfsReader.csproj" />
    <ProjectReference Include="..\SonicSearch.Contracts\SonicSearch.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>
</Project>
